const dateOnly = (value = new Date()) => new Date(value).toISOString().split("T")[0];

const toIso = (value) => new Date(value).toISOString();

const daysFromNow = (offset) => {
  const next = new Date();
  next.setDate(next.getDate() + offset);
  return next;
};

const buildInitialStore = () => {
  const users = [
    {
      id: "user_admin_001",
      name: "Admin User",
      email: "admin@company.com",
      role: "admin",
      department: "IT",
      employeeId: "EMP001",
      isActive: true,
    },
    {
      id: "user_hr_001",
      name: "HR Manager",
      email: "hr@company.com",
      role: "hr",
      department: "Human Resources",
      employeeId: "EMP002",
      isActive: true,
    },
    {
      id: "user_manager_001",
      name: "Department Manager",
      email: "manager@company.com",
      role: "manager",
      department: "Engineering",
      employeeId: "EMP003",
      isActive: true,
    },
    {
      id: "user_employee_001",
      name: "John Doe",
      email: "employee@company.com",
      role: "employee",
      department: "Sales",
      employeeId: "EMP004",
      isActive: true,
    },
  ];

  const employees = [
    { employeeId: "EMP001", name: "Admin User", department: "IT", isActive: true },
    { employeeId: "EMP002", name: "HR Manager", department: "Human Resources", isActive: true },
    { employeeId: "EMP003", name: "Department Manager", department: "Engineering", isActive: true },
    { employeeId: "EMP004", name: "John Doe", department: "Sales", isActive: true },
    { employeeId: "EMP005", name: "Sarah Williams", department: "Engineering", isActive: true },
    { employeeId: "EMP006", name: "Michael Brown", department: "Finance", isActive: true },
    { employeeId: "EMP007", name: "Emily Chen", department: "Marketing", isActive: true },
    { employeeId: "EMP008", name: "Robert Taylor", department: "Sales", isActive: true },
    { employeeId: "EMP009", name: "Jessica Martinez", department: "Engineering", isActive: true },
    { employeeId: "EMP010", name: "David Wilson", department: "HR", isActive: true },
  ];

  const leaveBalances = new Map(
    employees.map((employee) => [
      employee.employeeId,
      {
        employeeId: employee.employeeId,
        year: new Date().getFullYear(),
        medical: employee.employeeId === "EMP004" ? 9 : 12,
        vacation: employee.employeeId === "EMP004" ? 14 : 18,
        medicalUsed: employee.employeeId === "EMP004" ? 3 : 0,
        vacationUsed: employee.employeeId === "EMP004" ? 4 : 0,
      },
    ])
  );

  const leaveRequests = [
    {
      _id: "leave-1001",
      employeeId: "EMP004",
      employeeName: "John Doe",
      department: "Sales",
      leaveType: "medical",
      startDate: toIso(daysFromNow(-14)),
      endDate: toIso(daysFromNow(-13)),
      durationDays: 2,
      reason: "Medical consultation and recovery.",
      status: "approved",
      supportingDocument: null,
      documentMimeType: null,
      reviewedBy: "user_hr_001",
      reviewedAt: toIso(daysFromNow(-12)),
      hrComment: "",
      createdAt: toIso(daysFromNow(-15)),
    },
    {
      _id: "leave-1002",
      employeeId: "EMP004",
      employeeName: "John Doe",
      department: "Sales",
      leaveType: "vacation",
      startDate: toIso(daysFromNow(3)),
      endDate: toIso(daysFromNow(4)),
      durationDays: 2,
      reason: "Family travel plans.",
      status: "pending",
      supportingDocument: null,
      documentMimeType: null,
      reviewedBy: null,
      reviewedAt: null,
      hrComment: "",
      createdAt: toIso(daysFromNow(-1)),
    },
    {
      _id: "leave-1003",
      employeeId: "EMP005",
      employeeName: "Sarah Williams",
      department: "Engineering",
      leaveType: "vacation",
      startDate: toIso(daysFromNow(1)),
      endDate: toIso(daysFromNow(2)),
      durationDays: 2,
      reason: "Planned personal leave.",
      status: "pending",
      supportingDocument: null,
      documentMimeType: null,
      reviewedBy: null,
      reviewedAt: null,
      hrComment: "",
      createdAt: toIso(daysFromNow(-2)),
    },
    {
      _id: "leave-1004",
      employeeId: "EMP006",
      employeeName: "Michael Brown",
      department: "Finance",
      leaveType: "medical",
      startDate: toIso(daysFromNow(-5)),
      endDate: toIso(daysFromNow(-5)),
      durationDays: 1,
      reason: "Follow-up appointment.",
      status: "rejected",
      supportingDocument: null,
      documentMimeType: null,
      reviewedBy: "user_hr_001",
      reviewedAt: toIso(daysFromNow(-4)),
      hrComment: "Please attach the supporting document.",
      createdAt: toIso(daysFromNow(-6)),
    },
  ];

  const attendanceRecords = [
    {
      _id: "att-emp004-1",
      employeeId: "EMP004",
      employeeName: "John Doe",
      department: "Sales",
      date: dateOnly(daysFromNow(-2)),
      checkIn: toIso(new Date(`${dateOnly(daysFromNow(-2))}T08:58:00`)),
      checkOut: toIso(new Date(`${dateOnly(daysFromNow(-2))}T17:18:00`)),
      totalHours: 8.33,
      status: "present",
    },
    {
      _id: "att-emp004-2",
      employeeId: "EMP004",
      employeeName: "John Doe",
      department: "Sales",
      date: dateOnly(daysFromNow(-1)),
      checkIn: toIso(new Date(`${dateOnly(daysFromNow(-1))}T09:42:00`)),
      checkOut: toIso(new Date(`${dateOnly(daysFromNow(-1))}T17:06:00`)),
      totalHours: 7.4,
      status: "late",
    },
    {
      _id: "att-emp005-1",
      employeeId: "EMP005",
      employeeName: "Sarah Williams",
      department: "Engineering",
      date: dateOnly(new Date()),
      checkIn: toIso(new Date(`${dateOnly(new Date())}T08:51:00`)),
      checkOut: null,
      totalHours: 0,
      status: "present",
    },
    {
      _id: "att-emp006-1",
      employeeId: "EMP006",
      employeeName: "Michael Brown",
      department: "Finance",
      date: dateOnly(new Date()),
      checkIn: toIso(new Date(`${dateOnly(new Date())}T09:38:00`)),
      checkOut: null,
      totalHours: 0,
      status: "late",
    },
  ];

  const notifications = [
    {
      _id: "notif-5001",
      recipientId: "user_employee_001",
      recipientRole: "employee",
      message: "Your medical leave request was approved.",
      type: "leave_approved",
      relatedLeaveId: "leave-1001",
      createdAt: toIso(daysFromNow(-12)),
      read: false,
    },
    {
      _id: "notif-5002",
      recipientId: "user_hr_001",
      recipientRole: "hr",
      message: "John Doe submitted a vacation leave request.",
      type: "leave_submitted",
      relatedLeaveId: "leave-1002",
      createdAt: toIso(daysFromNow(-1)),
      read: false,
    },
  ];

  const payrollEmployees = [
    {
      id: "EMP-0034",
      name: "Sarah Williams",
      department: "Sales & Marketing",
      baseSalary: 8500,
      fixedAllowance: 1500,
      paymentMethod: "Direct Deposit",
      bankName: "First National Bank",
      accountNo: "**** 4567",
    },
    {
      id: "EMP-0012",
      name: "John Davis",
      department: "Engineering",
      baseSalary: 7800,
      fixedAllowance: 1200,
      paymentMethod: "Direct Deposit",
      bankName: "City Bank",
      accountNo: "**** 1220",
    },
    {
      id: "EMP-0028",
      name: "Emily Chen",
      department: "Finance",
      baseSalary: 7300,
      fixedAllowance: 950,
      paymentMethod: "Bank Transfer",
      bankName: "Union Trust",
      accountNo: "**** 7751",
    },
  ];

  const payrollRecords = [
    {
      id: "PR-202603-0001",
      employeeId: "EMP-0034",
      employeeName: "Sarah Williams",
      department: "Sales & Marketing",
      period: "March 2026",
      attendanceDays: 22,
      leaveDays: 0,
      gross: 12500,
      deductions: 3200,
      net: 9300,
      status: "Processed",
      paymentDate: "2026-03-31",
    },
    {
      id: "PR-202603-0002",
      employeeId: "EMP-0012",
      employeeName: "John Davis",
      department: "Engineering",
      period: "March 2026",
      attendanceDays: 21,
      leaveDays: 1,
      gross: 10600,
      deductions: 2595,
      net: 8005,
      status: "Processed",
      paymentDate: "2026-03-31",
    },
    {
      id: "PR-202602-0001",
      employeeId: "EMP-0028",
      employeeName: "Emily Chen",
      department: "Finance",
      period: "February 2026",
      attendanceDays: 20,
      leaveDays: 2,
      gross: 9800,
      deductions: 2620,
      net: 7180,
      status: "Pending",
      paymentDate: "2026-02-28",
    },
  ];

  const payslips = [
    {
      id: "PR-202603-0001",
      payrollId: "PR-202603-0001",
      employeeId: "EMP-0034",
      employeeName: "Sarah Williams",
      department: "Sales & Marketing",
      period: "2026-03",
      periodLabel: "March 2026",
      paymentDate: "2026-03-31",
      paymentMethod: "Direct Deposit",
      bankName: "First National Bank",
      accountNo: "**** 4567",
      earnings: [
        { label: "Basic Salary", amount: 8500 },
        { label: "Housing Allowance", amount: 1500 },
        { label: "Performance Bonus", amount: 2000 },
        { label: "Other Allowance", amount: 500 },
      ],
      deductions: [
        { label: "Federal Tax", amount: 1500 },
        { label: "Social Security", amount: 620 },
        { label: "Health Insurance", amount: 235 },
        { label: "Statutory Contribution", amount: 845 },
      ],
      gross: 12500,
      totalDeductions: 3200,
      net: 9300,
      attendanceDays: 22,
      leaveDays: 0,
    },
    {
      id: "PR-202603-0002",
      payrollId: "PR-202603-0002",
      employeeId: "EMP-0012",
      employeeName: "John Davis",
      department: "Engineering",
      period: "2026-03",
      periodLabel: "March 2026",
      paymentDate: "2026-03-31",
      paymentMethod: "Direct Deposit",
      bankName: "City Bank",
      accountNo: "**** 1220",
      earnings: [
        { label: "Basic Salary", amount: 7800 },
        { label: "Technical Allowance", amount: 1200 },
        { label: "Overtime", amount: 900 },
        { label: "Project Bonus", amount: 700 },
      ],
      deductions: [
        { label: "Federal Tax", amount: 1272 },
        { label: "Social Security", amount: 560 },
        { label: "Health Insurance", amount: 230 },
        { label: "Statutory Contribution", amount: 533 },
      ],
      gross: 10600,
      totalDeductions: 2595,
      net: 8005,
      attendanceDays: 21,
      leaveDays: 1,
    },
    {
      id: "PR-202602-0001",
      payrollId: "PR-202602-0001",
      employeeId: "EMP-0028",
      employeeName: "Emily Chen",
      department: "Finance",
      period: "2026-02",
      periodLabel: "February 2026",
      paymentDate: "2026-02-28",
      paymentMethod: "Bank Transfer",
      bankName: "Union Trust",
      accountNo: "**** 7751",
      earnings: [
        { label: "Basic Salary", amount: 7300 },
        { label: "Finance Allowance", amount: 950 },
        { label: "Overtime", amount: 420 },
        { label: "Accuracy Bonus", amount: 1130 },
      ],
      deductions: [
        { label: "Federal Tax", amount: 1176 },
        { label: "Social Security", amount: 520 },
        { label: "Health Insurance", amount: 224 },
        { label: "Statutory Contribution", amount: 700 },
      ],
      gross: 9800,
      totalDeductions: 2620,
      net: 7180,
      attendanceDays: 20,
      leaveDays: 2,
    },
  ];

  const performanceReviews = [
    {
      id: "PRV-Q1-2026-001",
      employeeName: "Sarah Williams",
      employeeId: "EMP-0034",
      department: "Sales & Marketing",
      reviewer: "Diana Carter",
      cycle: "Q1 2026",
      goalsScore: 4.6,
      competencyScore: 4.4,
      behaviorScore: 4.8,
      finalRating: 4.6,
      recommendation: "Promotion",
      status: "Completed",
    },
    {
      id: "PRV-Q1-2026-002",
      employeeName: "John Davis",
      employeeId: "EMP-0012",
      department: "Engineering",
      reviewer: "Rahul Perera",
      cycle: "Q1 2026",
      goalsScore: 4.1,
      competencyScore: 4.3,
      behaviorScore: 4,
      finalRating: 4.1,
      recommendation: "Bonus",
      status: "Completed",
    },
    {
      id: "PRV-Q2-2026-001",
      employeeName: "Emily Chen",
      employeeId: "EMP-0028",
      department: "Finance",
      reviewer: "Kevin Fernando",
      cycle: "Q2 2026",
      goalsScore: 3.7,
      competencyScore: 3.9,
      behaviorScore: 4.1,
      finalRating: 3.9,
      recommendation: "No Change",
      status: "In Progress",
    },
  ];

  const performanceGoals = [
    {
      id: "KPI-001",
      employeeName: "John Davis",
      employeeId: "EMP-0012",
      goal: "Reduce MTTR",
      metric: "Average MTTR (hours)",
      target: 3,
      current: 3.4,
      weight: 25,
      dueDate: "2026-06-30",
      lowerIsBetter: true,
    },
    {
      id: "KPI-002",
      employeeName: "Sarah Williams",
      employeeId: "EMP-0034",
      goal: "Increase qualified pipeline",
      metric: "Qualified leads",
      target: 120,
      current: 98,
      weight: 30,
      dueDate: "2026-06-30",
      lowerIsBetter: false,
    },
    {
      id: "KPI-003",
      employeeName: "Emily Chen",
      employeeId: "EMP-0028",
      goal: "Improve close accuracy",
      metric: "Accuracy %",
      target: 99,
      current: 97.6,
      weight: 20,
      dueDate: "2026-06-30",
      lowerIsBetter: false,
    },
  ];

  return {
    users,
    employees,
    leaveBalances,
    leaveRequests,
    attendanceRecords,
    notifications,
    payrollEmployees,
    payrollRecords,
    payslips,
    performanceReviews,
    performanceGoals,
    counters: {
      leave: 1005,
      notification: 5003,
    },
  };
};

const globalStoreKey = "__hrmsRuntimeStore";

if (!globalThis[globalStoreKey]) {
  globalThis[globalStoreKey] = buildInitialStore();
}

export const runtimeStore = globalThis[globalStoreKey];

export const helpers = {
  dateOnly,
  toIso,
};
